;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Optimizer configuration for sgOptimizer from Alchemy 3.2 with Raven plugins
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Global settings
[OPTIMIZE]
optimizationCount = 3
hierarchyCheck = true


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; igResizeImage
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[OPTIMIZATION1]
name = igResizeImage
widthFactor = -1
heightFactor = -1
minHeight = 1
minWidth = 1
maxHeight = 128
maxWidth = 128
resizeMipmap = false
useNextPowerOfTwo = true
filterType = 6


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; igQuantizeRaven
; convert to PNG8, better quality
; doesn't convert environment maps
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[OPTIMIZATION2]
name = igQuantizeRaven
imageList = 
imageListFilename = 
isExclude = true
isReduce = false
alphaPallete = true
eightBitTofourBitOnly = false


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; igConvertImage
; convert to PNG8, for environment maps
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[OPTIMIZATION3]
name = igConvertImage
format = x_8
order = DEFAULT
isExclude = exclude
convertIfSmaller = true
preserveAlpha = true
imageListFilename = 
