;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Optimizer configuration for sgOptimizer from Alchemy 3.2 with Raven plugins
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Global settings
[OPTIMIZE]
optimizationCount = 2
hierarchyCheck = true


; Note: igGeometryAttr1_5 and igGeometryAttr2 both seem to work


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; igResizeImage
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[OPTIMIZATION1]
name = igResizeImage
widthFactor = -1
heightFactor = -1
minHeight = 1
minWidth = 1
maxHeight = 512
maxWidth = 512
resizeMipmap = false
useNextPowerOfTwo = true
filterType = 6


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; igConvertImage
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[OPTIMIZATION2]
name = igConvertImage
format = DXT1
order = DEFAULT
isExclude = exclude
convertIfSmaller = false
preserveAlpha = false
imageListFilename = 
